apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgres
  namespace: ns-backstage
type: Opaque
stringData:
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: backstage-local-poc
  POSTGRES_DB: backstage
