apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ns-backstage
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - secretRef: { name: backstage-postgres }
          ports: [{ containerPort: 5432 }]
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: data
          emptyDir: {} # POC — sem persistência entre restarts do pod, é só pra validar a mecânica
---
