# echo-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Seixeiroo/idp.git
    targetRevision: main
    path: Poc/kubernetes/overlays/dev/ns-echo/echo
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-echo
  syncPolicy:
    automated: { prune: true, selfHeal: true }
