# Poc/kubernetes/argocd/dev/applications/platform-gateway.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Seixeiroo/idp.git
    targetRevision: main
    path: Poc/kubernetes/gateway/kind-poc
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: { prune: true, selfHeal: true }
